# Daniel Shapiro
# "I pledge my honor that I have abided by the Stevens Honor System." - Daniel Shapiro

cs392_thread: cs392_thread.o
	gcc -O0 -g cs392_thread.o -o cs392_thread -pthread

cs392_thread.o: cs392_thread.c
	gcc -O0 -g -o cs392_thread.o -c cs392_thread.c

clean:
	rm -rf *.o cs392_thread